from clases_foto1 import Boligrafo
from clases_foto2 import *

# Cargador
print(8*"*", "Cargador", 8*"*")
print(6*"*", "Cargador para camara", 6*"*")
carga_camara = Cargador("Canon", "Negro", "Mediano", "Cargador para camara")
carga_camara.imprimir()
print(6*"*", "Cargador para computadora", 6*"*")
carga_campu = Cargador("Apple", "Blanco", "Largo", "Cargador para computadora")
carga_campu.imprimir()
print()
# Celular
print(8*"*", "Celular", 8*"*")
cel = Celular("Nokia", "Negro", "Poco pequeño", "$4,000")
cel.imprimir()
print()
# Maletín
print(8*"*", "Celular", 8*"*")
portafolio = Maletin("Cuero", "Bottega Veneta", "Cuero", "$1,379", "Grande")
portafolio.imprimir()
print()
# Tripie
print(8*"*", "Tripie", 8*"*")
tripie = Tripie("Negro", "Grande", "Neewer", "$1,200")
tripie.imprimir()
print()
# Camisa
print(8*"*", "Camisa", 8*"*")
camisa = Camisa("SVPERVIA", "Blanca", "M", "$800")
camisa.imprimir()
print()
# Lentes
print(8*"*", "Lente", 8*"*")
print(6*"*", "Lente pequeño", 6*"*")
lente1 = Lente("Canon", "Negro", "Pequeño")
lente1.imprimir()
print(6*"*", "Lente mediano", 6*"*")
lente2 = Lente("Canon", "Negro", "Mediano")
lente2.imprimir()
print()
# Tapa protector de lente para cámara
print(8*"*", "Tapa para lente", 8*"*")
print(6*"*", "Tapa de lente pequeño", 6*"*")
tapa1 = Tapa_Lente("Canon", "Negro", "Pequeño")
tapa1.imprimir()
print(6*"*", "Tapa de lente mediano", 6*"*")
tapa2 = Tapa_Lente("Canon", "Negro", "Mediano")
tapa2.imprimir()
print()
# Pila 
print(8*"*", "Pila", 8*"*")
print(6*"*", "Pila 1", 6*"*")
pila1 = Pila("King", "10.8 W/h", "Mediana")
pila1.imprimir()
print(6*"*", "Pila 2", 6*"*")
pila2 = Pila("King", "10.8 W/h", "Mediana")
pila2.imprimir()
print()
# Computadora
print(8*"*", "Computadora", 8*"*")
compu = Computadora("Apple", "Gris claro", "$49,300", "Alta")
compu.imprimir()
print()
# Chamarra
print(8*"*", "Chamarra", 8*"*")
chaqueta = Chamarra("LV", "Mezclilla", "M", "$4,300")
chaqueta.imprimir()
print()
# Reloj
print(8*"*", "Reloj", 8*"*")
reloj_negro = Reloj("Rolex", "Negro", "$300,000", "Mediano")
reloj_negro.imprimir()
print()
# Zapatos
print(8*"*", "Zapatos", 8*"*")
zapatos = Zapato("Flexi", "Cuero", "25.5", "$2,000")
zapatos.imprimir()
print()
# Revista
print(8*"*", "Revista", 8*"*")
revist = Revista("JUICE", "En la portada están los The ChainSmokers", "Grande", "$149")
revist.imprimir()
print()
# Estuche 
print(8*"*", "Estuche para cámara", 8*"*")
estu_cam = Estuche("Columbia", "Negro", "Mediano", "Estuche para portar la cámara")
estu_cam.imprimir()
print()
# Boligrafos
print(8*"*", "Boligrafos", 8*"*")
print(6*"*", "Pluma", 6*"*")
pluma = Boligrafo("Pluma", "Negro", "Caligraphy pen", "Normal", "$190")
pluma.imprimir()
print(6*"*", "Lapiz 1", 6*"*")
lapiz1 = Boligrafo("Lapiz", "Negro", "Lyra", "Normal", "$19")
lapiz1.imprimir()
print(6*"*", "Lapiz 2", 6*"*")
lapiz2 = Boligrafo("Lapiz", "Negro", "Lyra", "Normal", "$19")
lapiz2.imprimir()
print(6*"*", "Lapiz 3", 6*"*")
lapiz3 = Boligrafo("Lapiz", "Negro", "Lyra", "Normal", "$19")
lapiz3.imprimir()
print(6*"*", "Color 1", 6*"*")
color1 = Boligrafo("Color", "Blanco", "Lyra", "Normal", "$19")
color1.imprimir()