from clases_foto1 import *

# Esmaltes
print(8*"*", "Esmaltes", 8*"*" )
print(6*"*", "Esmalte 1", 6*"*")
esmalte1 = Esmalte("Celeste", "Mediano", "Cilindrica")
esmalte1.imprimir()
print(6*"*", "Esmalte 2", 6*"*")
esmalte2 = Esmalte("Rosa claro", "Grande", "Cilindrica Fina")
esmalte2.imprimir()
print(6*"*", "Esmalte 3", 6*"*")
esmalte3 = Esmalte("Rosa oscuro con brillitos", "Mediano", "Diamante")
esmalte3.imprimir()
print(6*"*", "Esmalte 4",6*"*")
esmalte4 = Esmalte("Rosa", "Mediano", "Diamante")
esmalte4.imprimir()
print(6*"*", "Esmalte 5",6*"*")
esmalte5 = Esmalte("Rosa pastel", "Pequeño", "Cuadrada")
esmalte5.imprimir()
print(6*"*", "Esmalte 6",6*"*")
esmalte6 = Esmalte("Rojo", "Mediano", "Rectangular")
esmalte6.imprimir()
print(6*"*", "Esmalte 7",6*"*")
esmalte7 = Esmalte("Salmon", "Pequeño", "Cilindrico")
esmalte7.imprimir()
print()
# Marcos para fotos
print(8*"*", "Marcos para fotos", 8*"*" )
print(6*"*", "Marco 1", 6*"*")
marco1 = Marco_foto("Rosa pastel", "Rectangular", "Grande", "Tiene peganitas de estrellas en el contorno del marco y contiene una imagen de una dama.")
marco1.imprimir()
print(6*"*", "Marco 2", 6*"*")
marco2 = Marco_foto("Salmon", "Rectangular", "Grande", "Tiene pegatinas de estrellas en las esquinas del contorno del marco y contiene una imagen de un artista musical.")
marco2.imprimir()
print()
# Labiales
print(8*"*", "Labiales", 8*"*" )
print(6*"*", "Labial 1", 6*"*")
labial1 = Labial("Rosa", "Mediano", "Honey Love", "Cilindrica")
labial1.imprimir()
print(6*"*", "Labial 2", 6*"*")
labial2 = Labial("Rojo", "Mediano", "In Brave", "Cilindrica")
labial2.imprimir()
print(6*"*", "Labial 3", 6*"*")
labial3 = Labial("Rojo", "Mediano", "In Brave", "Cilindrica")
labial3.imprimir()
print()
# Cintas
print(8*"*", "Cintas", 8*"*" )
print(6*"*", "Cinta 1", 6*"*")
cinta1 = Cinta("Celeste", "5 cm", "Pequeño", "Papel")
cinta1.imprimir()
print(6*"*", "Cinta 2", 6*"*")
cinta2 = Cinta("Rosa", "5 cm", "Pequeño", "Papel")
cinta2.imprimir()
print(6*"*", "Cinta 3", 6*"*")
cinta3 = Cinta("Púrpura", "5 cm", "Pequeño", "Papel")
cinta3.imprimir()
print(6*"*", "Cinta 4", 6*"*")
cinta4 = Cinta("Verde pastel", "5 cm", "Pequeño", "Papel")
cinta4.imprimir()
print()
# Boligrafos
print(8*"*", "Boligrafos", 8*"*" )
print(6*"*", "Boligrafo 1", 6*"*")
bol1 = Boligrafo("Pluma", "Rosa fuerte", "BIC", "Normal", "$21")
bol1.imprimir()
print(6*"*", "Boligrafo 2", 6*"*")
bol2 = Boligrafo("Pluma", "Celeste", "Azor", "Normal", "$18")
bol2.imprimir()
print(6*"*", "Boligrafo 3", 6*"*")
bol3 = Boligrafo("Pluma", "Amarilla", "Azor", "Normal", "$18")
bol3.imprimir()
print(6*"*", "Boligrafo 4", 6*"*")
bol4 = Boligrafo("Pluma", "Roja", "Azor", "Normal", "$18")
bol4.imprimir()
print(6*"*", "Boligrafo 5", 6*"*")
bol5 = Boligrafo("Marcador", "Melon", "Crayola", "Normal", "$23")
bol5.imprimir()
print(6*"*", "Boligrafo 5", 6*"*")
bol6 = Boligrafo("Marcador", "Rosa pastel", "Crayola", "Normal", "$23")
bol6.imprimir()
print(6*"*", "Boligrafo 6", 6*"*")
bol7 = Boligrafo("Marcador", "Crema", "Crayola", "Normal", "$23")
bol7.imprimir()
print()
# Cuentas
print(8*"*", "Cuentas", 8*"*" )
print(6*"*", "Cuentas color rosa pastel", 6*"*")
cuentas_rosa = Cuenta("Rosa pastel", "Diminutas", "Redonda", "5")
cuentas_rosa.imprimir()
print(6*"*", "Cuentas color verde pastel", 6*"*")
cuentas_verdes = Cuenta("Verde pastel", "Diminutas", "Redonda", "6")
cuentas_verdes.imprimir()
print(6*"*", "Cuentas color naranja", 6*"*")
cuentas_naranjas = Cuenta("Naranja", "Diminutas", "Redonda", "4")
cuentas_naranjas.imprimir()
print(6*"*", "Cuentas color celeste", 6*"*")
cuentas_celeste = Cuenta("Celeste", "Diminutas", "Redonda", "1")
cuentas_celeste.imprimir()
print()
# Espejo
print(8*"*", "Espejo", 8*"*" )
print(6*"*", "Espejo con forma de corazón", 6*"*")
espejo_corazon = Espejo("Corazon", "Grande", "Rojo pasión")
espejo_corazon.imprimir()
print()
# Teléfono
print(8*"*", "Espejo", 8*"*" )
print(6*"*", "Telefono antigüo", 6*"*")
telefono_viejo = Telefono("Vintage", "Rosa pastel", "Grande")
telefono_viejo.imprimir()
print()
# Cuadernos
print(8*"*", "Cuadernos", 8*"*" )
print(6*"*", "Libreta naranja", 6*"*")
libreta1 = Cuaderno("Libreta", "Naranja", "Normal")
libreta1.imprimir()
print(6*"*", "Libreta rosa pastel", 6*"*")
libreta2 = Cuaderno("Libreta", "Rosa pastel", "Normal")
libreta2.imprimir()
print(6*"*", "Agenda", 6*"*")
libreta3 = Cuaderno("Agenda", "Celeste", "Normal")
libreta3.imprimir()
print()
# Posters
print(8*"*", "Posters", 8*"*" )
print(6*"*", "Poster de una persona", 6*"*")
poster1 = Poster("Una persona extraña posando con lentes de sol", "Mediano")
poster1.imprimir()
print(6*"*", "Poster de frases", 6*"*")
poster2 = Poster("Contiene una frase motivacional", "Mediano")
poster2.imprimir()
print(6*"*", "Poster de la playa", 6*"*")
poster3 = Poster("Se ve un grupo de personas refrescandose en la playa", "Mediano")
poster3.imprimir()
print()
# Tijeras
print(8*"*", "Tijeras", 8*"*" )
tijeras = Tijera("Punta en pico", "Celeste", "Medianas")
tijeras.imprimir()
print()
# Pegamento
print(8*"*", "Pegamento", 8*"*" )
resistol = Pegamento("En barra", "Rosa pastel", "Grande")
resistol.imprimir()
print()
# Pinzas
print(8*"*", "Pinzas", 8*"*" )
print(6*"*", "Pinzas 1", 6*"*")
pinzas1 = Pinza("Celeste", "Pequeña", "Plastico")
pinzas1.imprimir()
print(6*"*", "Pinzas 2 ", 6*"*")
pinzas2 = Pinza("Rosa", "Pequeña", "Plastico")
pinzas2.imprimir()
print(6*"*", "Pinzas 3 ", 6*"*")
pinzas3 = Pinza("Amarilla", "Pequeña", "Plastico")
pinzas3.imprimir()
print(6*"*", "Pinzas 4 ", 6*"*")
pinzas4 = Pinza("Coral", "Pequeña", "Plastico")
pinzas4.imprimir()
print(6*"*", "Pinzas 5 ", 6*"*")
pinzas5 = Pinza("Naranja", "Pequeña", "Plastico")
pinzas5.imprimir()
print(6*"*", "Pinzas 6 ", 6*"*")
pinzas6 = Pinza("Morada", "Pequeña", "Plastico")
pinzas6.imprimir()
print()
# Pegatinas
print(8*"*", "Pegatinas", 8*"*" )
print(6*"*", "Pegatinas con forma de estrella", 6*"*")
pega_estrella = Pegatina("Estrellita", "Celeste", "Pequeña", "10")
pega_estrella.imprimir()
print(6*"*", "Pegatinas con forma de diamante", 6*"*")
pega_diamante = Pegatina("Diamante", "Platino", "Pequeña", "10")
pega_diamante.imprimir()
print(6*"*", "Pegatinas con forma de corazón", 6*"*")
pega_corazon = Pegatina("Corazon", "Plateado", "Pequeña", "15")
pega_corazon.imprimir()