from clasesfoto1 import *

#Espejos
print("***Espejos***")
espejo1 = Espejo (1,"rosa","justice","corazon","pequeño")
espejo1.info()
#Telefonos
print("***Telefonos***")
telefono1 = Telefono (1,"rosa","vintage","pequeño")
telefono1.info()
#Esmaltes
print("***Esmaltes***")
esmalte1 = Esmalte (1,"rojo","h&m","cubo")
esmalte1.info()
esmalte2 = Esmalte (2,"rosa","amazon","cilindro")
esmalte2.info()
esmalte3 = Esmalte (3,"rosa pastel","h&m","cubo")
esmalte3.info()
esmalte4 = Esmalte (4,"brillos","h&m","cubo")
esmalte4.info()
esmalte5 = Esmalte (5,"lila","amazon","cilindro")
esmalte5.info()
esmalte6 = Esmalte (6,"blanco","h&m","cubo")
esmalte6.info()
esmalte7 = Esmalte (7,"dorado","amazon","cubo")
esmalte7.info()
#Boligrafos
print("***Boligrafos***")
boligrafo1 = Boligrafos (1 ,"rosa","bic","pequeño")
boligrafo1.info()
boligrafo2 = Boligrafos (2 ,"naranja","onix","pequeño")
boligrafo2.info()
boligrafo3 = Boligrafos (3 ,"amarillo","bic","pequeño")
boligrafo3.info()
boligrafo4 = Boligrafos (4 ,"azul","bic","pequeño")
boligrafo4.info()
#Tijeras
print("***Tijeras***")
tijera1 = Tijeras(1,"azul","bic")
tijera1.info()
#Cintas
print("***Cintas***")
cinta1 = Cintas (1,"rosa","paper mate","circular")
cinta1.info()
cinta2 = Cintas (2,"lila","paper mate","circular")
cinta2.info()
cinta3 = Cintas (3,"verde","paper mate","circular")
cinta3.info()
#Libreta
print("***Libretas***")
libreta1 = Libretas (1,"azul","scribe",200)
libreta1.info()
libreta2 = Libretas (2,"morada","scribe",120)
libreta2.info()
libreta3 = Libretas (3,"morada","scribe",160)
libreta3.info()
#Portaretratos
print("***Portaretrato***")
portaretrato1= Portaretratos(1,"blanco con flores","amazon","8.5 x 11 cm")
portaretrato1.info()
portaretrato2= Portaretratos(2,"blano con estrellas","amazon","8.5 x 11 cm")
portaretrato2.info()
#Gloss
print("***Gloss***")
gloss1= Gloss (1,"rojo", "mac")
gloss1.info()
gloss2= Gloss (2,"rosa", "rare beauty")
gloss2.info()
gloss3= Gloss (3,"blanco", "fenty")
gloss3.info()
#Pegamentos
print("***Pegamentos***")
pegamento1 = Pegamentos (1,"rosa","pritt","grnade")
pegamento1.info()
#Cucas
print("***Cucas***")
cuca1 = Cucas (1,"amarillo", "mini")
cuca1.info()
cuca2 = Cucas (2,"naranja", "mini")
cuca2.info()
cuca3 = Cucas (3,"rosa", "mini")
cuca3.info()
cuca4 = Cucas (4,"azul", "mini")
cuca4.info()
cuca5 = Cucas (5,"morada", "mini")
cuca5.info()
#´Perlas
print("***Perlas***")
perla1 = Perlas (1,"rosa")
perla1.info()
perla2 = Perlas (2,"rosa")
perla2.info()
perla3 = Perlas (3,"rosa")
perla3.info()
perla4 = Perlas (4,"rosa")
perla4.info()
perla5 = Perlas (5,"rosa")
perla5.info()
perla6 = Perlas (6,"naranja")
perla6.info()
perla7 = Perlas (7,"naranja")
perla7.info()
perla8 = Perlas (8,"naranja")
perla8.info()
perla9 = Perlas (9,"naranja")
perla9.info()
perla10 = Perlas (10,"amarillo")
perla10.info()
perla11 = Perlas (11,"amarillo")
perla11.info()
perla12 = Perlas (12,"amarillo")
perla12.info()
perla13= Perlas (13,"amarillo")
perla13.info()
perla14 = Perlas (14,"amarillo")
perla14.info()
perla15 = Perlas (15,"amarillo")
perla15.info()
perla16 = Perlas (16,"celeste")
perla16.info()
perla17 = Perlas (17,"verde")
perla17.info()
perla18 = Perlas (18,"aqua")
perla18.info()
perla19 = Perlas (19,"blanca")
perla19.info()
perla20 = Perlas (20,"blanca")
perla20.info()
#Pegantinas
print("***Pegantinas***")
pegantina1 = Pegantinas (1,"celeste","diamante")
pegantina1.info()
pegantina2 = Pegantinas (2,"rosa","corazon")
pegantina2.info()
pegantina3 = Pegantinas (3,"lila","circulo")
pegantina3.info()
#Hojas
print("***Hojas***")
hoja1= Hojas (1,"blanca", "carta")
hoja1.info()
hoja2= Hojas (2,"celeste", "carta")
hoja2.info()
hoja3= Hojas (3,"rosa", "carta")
hoja3.info()
hoja4= Hojas (4,"blanca", "carta")
hoja4.info()
#Plumones
print("***Plumones***")
plumon1 = Plumones (1,"morado","crayola")
plumon1.info()
plumon2 = Plumones (1,"rosa","crayola")
plumon2.info()
plumon3 = Plumones (1,"nude","crayola")
plumon3.info()






