from clasesfoto1 import (Libreta, Espejo, Marco, Esmalte, Tijeras, Plumas, Plumones, Pinza_pelo, Pegamento, Cinta, Stickers, Cuentas, Maquillaje, Fotos, Regla)

libreta1 = Libreta(1, "Azul", "Mediana", "Cosida")
libreta1.info_libreta()
libreta2 = Libreta(2, "Rosa", "Mediana", "De espiral")
libreta2.info_libreta()
libreta3 = Libreta(3, "Azul y morado", "Mediana", "De espiral")
libreta3.info_libreta()
print("")

espejo1 = Espejo(1, "Rosa", "Pequeño", "Corazón")
espejo1.info_espejo()
print("")

marco1 = Marco(1, "Blanco", "Mediano", "Rectangular", "Flores y estrellas")
marco1.info_marco()
marco2 = Marco(2, "Blanco", "Mediano", "Rectangular", "Estrellas")
marco2.info_marco()
print("")

esmalte1 = Esmalte(1, "Azul", "Cilindro")
esmalte1.info_esmalte()
esmalte2 = Esmalte(2, "Blanco", "Cilindro")
esmalte2.info_esmalte()
esmalte3 = Esmalte(3, "Morado", "Esfera")
esmalte3.info_esmalte()
esmalte4 = Esmalte(4, "Rosa", "Cubo")
esmalte4.info_esmalte()
esmalte5 = Esmalte(5, "Rojo", "Cubo")
esmalte5.info_esmalte()
esmalte6 = Esmalte(6, "Azul", "Cilindro")
esmalte6.info_esmalte()
esmalte7 = Esmalte(7, "Rosa", "Dodecaedro")
esmalte7.info_esmalte()
esmalte8 = Esmalte(2, "Blanco", "Cilindro")
esmalte8.info_esmalte()
esmalte9 = Esmalte(9, "Rojo", "Cilindro")
esmalte9.info_esmalte()
print("")

tijeras1 = Tijeras(1, "Azul", "Plástico y metal")
tijeras1.info_tijeras()
print("")

pluma1 = Plumas(1, "Rosa", "1", "Bic", "Plástico")
pluma1.info_plumas()
pluma2 = Plumas(2, "Azul", "1", "Bic", "Plástico")
pluma2.info_plumas()
pluma3 = Plumas(3, "Amarillo", "1", "Bic", "Plástico")
pluma3.info_plumas()
pluma4 = Plumas(4, "Rojo", "1", "Bic", "Plástico")
pluma4.info_plumas()
print("")

plumon1 = Plumones(1, "Rosa", "2", "Sharpie", "Plástico")
plumon1.info_plumon()
plumon2 = Plumones(2, "Morado", "2", "Sharpie", "Plástico")
plumon2.info_plumon()
plumon3 = Plumones(3, "Naranja", "2", "Sharpie", "Plástico")
plumon3.info_plumon()
print("")

pinza1 = Pinza_pelo(1, "Azul" ,"Pequeño", "Plástico")
pinza1.info_pinza()
pinza2 = Pinza_pelo(2, "Rosa" ,"Pequeño", "Plástico")
pinza2.info_pinza()
pinza3 = Pinza_pelo(3, "Amarillo" ,"Pequeño", "Plástico")
pinza3.info_pinza()
pinza4 = Pinza_pelo(4, "Naranja" ,"Pequeño", "Plástico")
pinza4.info_pinza()
pinza5 = Pinza_pelo(5, "Morado" ,"Pequeño", "Plástico")
pinza5.info_pinza()
pinza6 = Pinza_pelo(6, "Rojo" ,"Pequeño", "Plástico")
pinza6.info_pinza()
print("")

pegamento1 = Pegamento(1, "Rosa", "Mediano", "Cilindro")
pegamento1.info_pegamento
print("")

cinta1 = Cinta(1, "Rosa", "Pequeño", "5")
cinta1.info_cinta()
cinta2 = Cinta(2, "Verde", "Pequeño", "5")
cinta2.info_cinta()
cinta3 = Cinta(3, "Morado", "Pequeño", "5")
cinta3.info_cinta()
print("")

sticker1 = Stickers(1, "Amarillo", "Estrella")
sticker1.info_sticker()
sticker2 = Stickers(2, "Rosa", "Flor")
sticker2.info_sticker()
sticker3 = Stickers(3, "Plateado", "Luna")
sticker3.info_sticker()
sticker4 = Stickers(4, "Plateado", "Flor")
sticker4.info_sticker()
sticker5 = Stickers(5, "Azul", "Estrella")
sticker5.info_sticker()
sticker6 = Stickers(6, "Amarillo", "Corazón")
sticker6.info_sticker()
print("")

cuenta1 = Cuentas(1, "Blanco", "Plástico")
cuenta1.info_cuentas()
cuenta2 = Cuentas(2, "Naranja", "Plástico")
cuenta2.info_cuentas()
cuenta3 = Cuentas(3, "Verde", "Plástico")
cuenta3.info_cuentas()
cuenta4 = Cuentas(4, "Rosa", "Plástico")
cuenta4.info_cuentas()
cuenta5 = Cuentas(5, "Rojo", "Plástico")
cuenta5.info_cuentas()
print("")

maquillaje1 = Maquillaje(1, "Rosa", "Pequeño", "9")
maquillaje1.info_maquillaje()
print("")

foto1 = Fotos(1, "Una persona", "18x24", "Papel")
foto1.info_fotos()
foto2 = Fotos(2, "Una persona", "18x24", "Papel")
foto2.info_fotos()
foto3 = Fotos(3, "Un teléfono", "6x15", "Papel")
foto3.info_fotos()
foto4 = Fotos(4, "Una frase", "16x20", "Papel")
foto4.info_fotos()
foto5 = Fotos(1, "Una persona", "18x24", "Papel")
foto5.info_fotos()
foto6 = Fotos(6, "Varias personas en la playa", "18x24", "Papel")
foto6.info_fotos()
print("")

regla1 = Regla(1, "Rosa", "30", "Plástico")
regla1.info_regla()