from clasesfoto1 import Esmaltes, Gloss, Marco, Pegamento, Libreta, Espejo, Telefono, Pegatinas, Marcatextos, Cinta, Caja_de_maquillaje, Pluma_, Regla, Tijeras, Pinza, Cuentas

print("")
esmalte = Esmaltes(1, "azul", "25", "vidrio", "plastico")
esmalte.atributos_esmaltes()
print("")
esmalte = Esmaltes(2, "blanco", "25", "vidrio", "plastico")
esmalte.atributos_esmaltes()
print("")
esmalte = Esmaltes(3, "rojo", "25", "vidrio", "plastico")
esmalte.atributos_esmaltes()
print("")
esmalte = Esmaltes(4, "rosa palo", "25", "vidrio", "plastico")
esmalte.atributos_esmaltes()
print("")
esmalte = Esmaltes(5, "rosa escarchado", "25", "vidrio", "plastico")
esmalte.atributos_esmaltes()
print("")
esmalte = Esmaltes(6, "rosa", "25", "vidrio", "plastico")
esmalte.atributos_esmaltes()
print("")
esmalte = Esmaltes(7, "plateado", "25", "vidrio", "plastico")
esmalte.atributos_esmaltes()
print("")
gloss = Gloss(1, "rosa", "15", "vidrio", "plastico")
gloss.atributos_gloss()
print("")
gloss = Gloss(2, "rojo", "15", "vidrio", "plastico")
gloss.atributos_gloss()
print("")
gloss = Gloss(3, "blanco", "15", "vidrio", "plastico")
gloss.atributos_gloss()
print("")
marco = Marco(1, "15", "21", "madera", "beige")
marco.atributos_marco()
print("")
marco = Marco(2, "15", "21", "madera", "beige")
marco.atributos_marco()
print("")
pegamento = Pegamento(1, "barra", "rosa", "grande", "plastico")
pegamento.atributos_pegam()
print("")
lib = Libreta(1, "celeste", "29", "21", "dura")
lib.atributos_lib()
print("")
lib = Libreta(2, "rosa", "29", "21", "dura")
lib.atributos_lib()
print("")
lib = Libreta(3, "rosa", "29", "21", "dura")
lib.atributos_lib()
print("")
espejo = Espejo(1, "corazón", "rojo", "25", "plastico")
espejo.atributos_espejo()
print("")
telefono = Telefono(1, "rosa", "rosa palo", "alambrico", "circulo")
telefono.atributos_tel()
print("")
pegatinas = Pegatinas(1, "pequeño", "azul", "diamante", "plastico")
pegatinas.atributos_pegatinas()
print("")
pegatinas = Pegatinas(2, "pequeño", "rosa", "perla", "plastico")
pegatinas.atributos_pegatinas()
print("")
pegatinas = Pegatinas(3, "pequeño", "rosa pastel", "corazón", "plastico")
pegatinas.atributos_pegatinas()
print("")
pegatinas = Pegatinas(4, "pequeño", "dorado", "estrella", "plastico")
pegatinas.atributos_pegatinas()
print("")
pegatinas = Pegatinas(5, "pequeño", "morado", "luna", "plastico")
pegatinas.atributos_pegatinas()
print("")
marcatextos = Marcatextos(1, "delgado", "amarillo", "15", "fina")
marcatextos.atributos_marcatextos()
print("")
marcatextos = Marcatextos(2, "delgado", "lila", "15", "fina")
marcatextos.atributos_marcatextos()
print("")
marcatextos = Marcatextos(3, "delgado", "rosa", "15", "fina")
marcatextos.atributos_marcatextos()
print("")
cinta = Cinta(1, "rosa", "3", "5", "170")
cinta.atributos_cinta()
print("")
cinta = Cinta(2, "rosa brilloso", "3", "5", "170")
cinta.atributos_cinta()
print("")
cinta = Cinta(3, "verde", "3", "5", "170")
cinta.atributos_cinta()
print("")
cinta = Cinta(4, "azul", "3", "5", "170")
cinta.atributos_cinta()
print("")
maqui = Caja_de_maquillaje(1, "plástico", "rosa", "9", "700")
maqui.atributos_c_maqui()
print("")
pluma = Pluma_(1, "rosa", "15", "rosa", "fina")
pluma.atributos_pluma()
print("")
pluma = Pluma_(2, "azul", "15", "azul", "fina")
pluma.atributos_pluma()
print("")
pluma = Pluma_(3, "amarillo", "15", "amarilla", "fina")
pluma.atributos_pluma()
print("")
pluma = Pluma_(4, "naranja", "15", "naranja", "fina")
pluma.atributos_pluma()
print("")
regla = Regla(1, "rosa", "30", "triangulo", "plastico")
regla.atributos_regla()
print("")
tijera = Tijeras(1, "celeste", "infantil", "redonda", "110")
tijera.atributos_tijera()
print("")
pinza = Pinza(1, "chica", "azul", "plastico", "15")
pinza.atributos_pinza()
print("")
pinza = Pinza(2, "chica", "amarillo", "plastico", "15")
pinza.atributos_pinza()
print("")
pinza = Pinza(3, "chica", "rosa", "plastico", "15")
pinza.atributos_pinza()
print("")
pinza = Pinza(4, "chica", "rosa pastel", "plastico", "15")
pinza.atributos_pinza()
print("")
pinza = Pinza(5, "chica", "naranja", "plastico", "15")
pinza.atributos_pinza()
print("")
pinza = Pinza(6, "chica", "morado", "plastico", "15")
pinza.atributos_pinza()
print("")
cuentas = Cuentas(1, "pequeña", "naranja", "acrilico", "5")
cuentas.atributos_cuentas()
print("")
cuentas = Cuentas(2, "pequeña", "amarillo", "acrilico", "5")
cuentas.atributos_cuentas()
print("")
cuentas = Cuentas(3, "pequeña", "blanco", "acrilico", "5")
cuentas.atributos_cuentas()
print("")
cuentas = Cuentas(4, "pequeña", "verde", "acrilico", "5")
cuentas.atributos_cuentas()
print("")
cuentas = Cuentas(5, "pequeña", "rojo", "acrilico", "5")
cuentas.atributos_cuentas()
print("")
cuentas = Cuentas(6, "pequeña", "turquesa", "acrilico", "5")
cuentas.atributos_cuentas()