from clasesfoto2 import Pila_portatil, Camisa, Celular, Reloj, Revista, Lentes_camara, Baterias_camara, Portafolio, Tripie, Macbook, Zapatos, Cable, Plumas, Lapices, Estuche_camara, Tapas_camara

print("")
pila_p = Pila_portatil(1, "negro", "10000", "alambrica", "5")
pila_p.atributos_pila_P()
print("")
camisa1 = Camisa(1, "SVEPERBIA", "blanco", "mediana", "algodon")
camisa1.atributos_camisa()
print("")
camisa2 = Camisa(2, "SVEPERBIA", "negro", "mediana", "algodon",)
camisa2.atributos_camisa()
print("")
celular = Celular(1, "1.5", "touch", "negro", "6")
celular.atributos_cel()
print("")
reloj = Reloj(1, "negro", "25", "analogo", "hule")
reloj.atributos_reloj()
print("")
revista = Revista(1, "32", "comunicación", "blanco", "120")
revista.atributos_revista()
print("")
lent = Lentes_camara(1, "5", "negro", "10", "80")
lent.atributos_lentes()
print("")
lent2 = Lentes_camara(2, "4", "negro", "8", "60")
lent2.atributos_lentes()
print("")
bat = Baterias_camara(1, "5000", "2.5", "negro", "350")
bat.atributos_bat()
print("")
bat2 = Baterias_camara(2, "5000", "2.5", "negro", "350")
bat2.atributos_bat()
print("")
port = Portafolio(1, "22", "piel", "café", "600")
port.atributos_port()
print("")
trip = Tripie(1, "negro", "110", "EXCELL", "450")
trip.atributos_trip()
print("")
mac = Macbook(1, "Apple", "IOS", "gris", "12")
mac.atributos_mac()
print("")
zap = Zapatos(1, "café", "mocasin", "27", "piel")
zap.atributos_zapatos()
print("")
cab = Cable(1, "blanco", "100", "2", "20")
cab.atributos_cable()
print("")
cab2 = Cable(2, "blanco", "110", "2", "20")
cab2.atributos_cable()
print("")
cab3 = Cable(3, "negro", "15", "2", "20")
cab3.atributos_cable()
print("")
plu = Plumas(1, "plastico","negro", "negra", "12", "1")
plu.atributos_pluma()
print("")
lap = Lapices(1, "madera", "negro", "15", "grafito")
lap.atributos_lapiz()
print("")
lap2 = Lapices(2, "madera", "negro", "15", "grafito")
lap2.atributos_lapiz()
print("")
lap3 = Lapices(3, "madera", "negro", "15", "grafito")
lap3.atributos_lapiz()
print("")
lap4 = Lapices(4, "madera", "amarillo", "15", "grafito")
lap4.atributos_lapiz()
print("")
est = Estuche_camara(1, "negro", "mediano", "tela", "90")
est.atributos_estu()
print("")
tap = Tapas_camara(1, "negro", "canon", "4", "15")
tap.atributos_tapas()
print("")
tap2 = Tapas_camara(2, "negro", "canon", "4", "15")
tap2.atributos_tapas()
print("")
tap3 = Tapas_camara(3, "negro", "canon", "4", "15")
tap3.atributos_tapas()
print("")