from clasesfoto1 import Esmaltes, Gloss, Marco, Pegamento, Libreta, Espejo, Telefono, Pegatinas, Marcatextos, Cinta, Caja_de_maquillaje, Pluma_, Regla, Tijeras, Pinza, Cuentas

print("")
esmalte = Esmaltes(1, "azul", "25", "vidrio", "plastico")
esmalte.atributos_esmaltes()
print("")
esmalte = Esmaltes(2, "blanco", "25", "vidrio", "plastico")
esmalte.atributos_esmaltes()
print("")
esmalte = Esmaltes(3, "rojo", "25", "vidrio", "plastico")
esmalte.atributos_esmaltes()
print("")
esmalte = Esmaltes(4, "rosa palo", "25", "vidrio", "plastico")
esmalte.atributos_esmaltes()
print("")
esmalte = Esmaltes(5, "rosa escarchado", "25", "vidrio", "plastico")
esmalte.atributos_esmaltes()
print("")
esmalte = Esmaltes(6, "rosa", "25", "vidrio", "plastico")
esmalte.atributos_esmaltes()
print("")
esmalte = Esmaltes(7, "plateado", "25", "vidrio", "plastico")
esmalte.atributos_esmaltes()
print("")
gloss = Gloss(1, "rosa", "15", "vidrio", "plastico")
gloss.atributos_gloss()
print("")
gloss = Gloss(2, "rojo", "15", "vidrio", "plastico")
gloss.atributos_gloss()
print("")
gloss = Gloss(3, "blanco", "15", "vidrio", "plastico")
gloss.atributos_gloss()
print("")
marco = Marco(1, "15", "21", "madera")
marco.atributos_marco()
print("")
marco = Marco(2, "15", "21", "madera")
marco.atributos_marco()
print("")
pegamento = Pegamento(1, "rosa", "grande")
pegamento.atributos_pegam()
print("")
lib = Libreta(1, "celeste", "29", "21")
lib.atributos_lib()
print("")
lib = Libreta(2, "rosa", "29", "21")
lib.atributos_lib()
print("")
lib = Libreta(3, "rosa", "29", "21")
lib.atributos_lib()
print("")
espejo = Espejo(1, "corazón", "rojo", "25")
espejo.atributos_espejo()
print("")
telefono = Telefono(1, "rosa pastel", "alambrico", "circulo")
telefono.atributos_tel()
print("")
pegatinas = Pegatinas(1, "azul", "diamante", "plastico")
pegatinas.atributos_pegatinas()
print("")
pegatinas = Pegatinas(2, "rosa", "perla", "plastico")
pegatinas.atributos_pegatinas()
print("")
pegatinas = Pegatinas(3, "rosa pastel", "corazón", "plastico")
pegatinas.atributos_pegatinas()
print("")
pegatinas = Pegatinas(4, "dorado", "estrella", "plastico")
pegatinas.atributos_pegatinas()
print("")
pegatinas = Pegatinas(5, "morado", "luna", "plastico")
pegatinas.atributos_pegatinas()
print("")
marcatextos = Marcatextos(1, "amarillo", "15", "fina")
marcatextos.atributos_marcatextos()
print("")
marcatextos = Marcatextos(2, "lila", "15", "fina")
marcatextos.atributos_marcatextos()
print("")
marcatextos = Marcatextos(3, "rosa", "15", "fina")
marcatextos.atributos_marcatextos()
print("")
cinta = Cinta(1, "rosa", "3", "5")
cinta.atributos_cinta()
print("")
cinta = Cinta(2, "rosa brilloso", "3", "5")
cinta.atributos_cinta()
print("")
cinta = Cinta(3, "verde", "3", "5")
cinta.atributos_cinta()
print("")
cinta = Cinta(4, "azul", "3", "5")
cinta.atributos_cinta()
print("")
maqui = Caja_de_maquillaje(1, "plástico", "rosa", "9")
maqui.atributos_c_maqui()
print("")
pluma = Pluma_(1, "rosa", "15", "rosa", "fina")
pluma.atributos_pluma()
print("")
pluma = Pluma_(2, "azul", "15", "azul", "fina")
pluma.atributos_pluma()
print("")
pluma = Pluma_(3, "amarillo", "15", "amarilla", "fina")
pluma.atributos_pluma()
print("")
pluma = Pluma_(4, "naranja", "15", "naranja", "fina")
pluma.atributos_pluma()
print("")
regla = Regla(1, "rosa", "30", "plastico")
regla.atributos_regla()
print("")
tijera = Tijeras(1, "celeste", "infantil", "redonda")
tijera.atributos_tijera()
print("")
pinza = Pinza(1, "chica", "azul", "plastico")
pinza.atributos_pinza()
print("")
pinza = Pinza(2, "chica", "amarillo", "plastico")
pinza.atributos_pinza()
print("")
pinza = Pinza(3, "chica", "rosa", "plastico")
pinza.atributos_pinza()
print("")
pinza = Pinza(4, "chica", "rosa pastel", "plastico")
pinza.atributos_pinza()
print("")
pinza = Pinza(5, "chica", "naranja", "plastico")
pinza.atributos_pinza()
print("")
pinza = Pinza(6, "chica", "morado", "plastico")
pinza.atributos_pinza()
print("")
cuentas = Cuentas(1, "naranja", "acrilico")
cuentas.atributos_cuentas()
print("")
cuentas = Cuentas(2, "amarillo", "acrilico")
cuentas.atributos_cuentas()
print("")
cuentas = Cuentas(3, "blanco", "acrilico")
cuentas.atributos_cuentas()
print("")
cuentas = Cuentas(4, "verde", "acrilico")
cuentas.atributos_cuentas()
print("")
cuentas = Cuentas(5, "rojo", "acrilico")
cuentas.atributos_cuentas()
print("")
cuentas = Cuentas(6, "turquesa", "acrilico")
cuentas.atributos_cuentas()