from clasesfoto1 import Pila_portatil, Camisa, Camisan, Celular, Reloj, Revista, Lentes_camara, Baterias_camara, Portafolio, Tripie, Macbook, Zapatos, Cable, Plumas, Lapices, Estuche_camara, Tapas_camara

print("")
pila_p = Pila_portatil("negro", "5")
pila_p.atributos_pila_P()
print("")
camisa = Camisa("SVEPERBIA", "blanco", "mediana", "algodon", "12")
camisa.atributos_camisa()
print("")
camisan = Camisan("SVEPERBIA", "negro", "mediana", "algodon")
camisan.atributos_camisa_n()
print("")
celular = Celular("negro", "6")
celular.atributos_cel()
print("")
reloj = Reloj("negro", "25", "analogo")
reloj.atributos_reloj()
print("")
revista = Revista("32", "comunicación", "blanco")
revista.atributos_revista()
print("")
lent = Lentes_camara("5", "negro", "10")
lent.atributos_lentes()
print("")
bat = Baterias_camara("5000", "2.5", "negro")
bat.atributos_bat()
print("")
port = Portafolio("22", "piel", "café")
port.atributos_port()
print("")
trip = Tripie("negro", "110", "EXCELL")
trip.atributos_trip()
print("")
mac = Macbook("Apple", "gris", "12")
mac.atributos_mac()
print("")
zap = Zapatos("café", "mocasin", "27", "piel")
zap.atributos_zapatos()
print("")
cab = Cable("blanco", "200")
cab.atributos_cable()
print("")
plu = Plumas("plastico","negro", "negra", "12", "1")
plu.atributos_pluma()
print("")
lap = Lapices("madera", "negro", "15", "grafito")
lap.atributos_lapiz()
print("")
est = Estuche_camara("negro", "mediano", "tela")
est.atributos_estu()
print("")
tap = Tapas_camara("negro", "canon")
tap.atributos_tapas()
print("")