from clasesFoto1 import Pluma,Tijera,Libreta,Regla,Espejo,Estuche,Pegamento,Marco,Esmalte,Labial,Cuenta,Marcador,Cinta,Telefono,Sticker,Pinza,Postal

pluma1 = Pluma("Rojo","7cm","BIC","$5")
pluma1.imprimir() 
pluma2 = Pluma("Azul","7cm","BIC","$5")
pluma2.imprimir()
pluma3 = Pluma("Verde","7cm","BIC","$5")
pluma3.imprimir()
pluma4 = Pluma("Naranja","7cm","BIC","$5")
pluma4.imprimir()

marcador1 = Marcador("Naranja","7cm","Stabilo","$10")
marcador1.imprimir()
marcador2 = Marcador("Morado","7cm","Stabilo","$10")
marcador2.imprimir()

tijera1 = Tijera("Azul","15cm","Mylin","$30")
tijera1.imprimir()

libreta1 = Libreta("Rosa", 100,"norma", "$40")
libreta1.imprimir()
libreta2 = Libreta("Morada", 100,"norma", "$40")
libreta2.imprimir()

espejo = Espejo("Corazon", "Rosa", "20x12","$120")
espejo.imprimir()

estuche = Estuche("Morado","Cuadrado", "10x10cm","$40")

regla = Regla("Rosa","Triangular","30cm","$30")

pegamento = Pegamento("Pegamento de barra", "Pritt","7cm","$50")
pegamento.imprimir()

esmalte1 = Esmalte("Azul","$40","GELAZE","permanente")
esmalte1.imprimir()
esmalte2 = Esmalte("Rojo","$40","GELAZE","permanente")
esmalte2.imprimir()
esmalte3 = Esmalte("Crema","$40","GELAZE","permanente")
esmalte3.imprimir()
esmalte4 = Esmalte("Rosa","$40","GELAZE","permanente")
esmalte4.imprimir()
esmalte5 = Esmalte("Rosa","$40","GELAZE","permanente")
esmalte5.imprimir()
esmalte6 = Esmalte("Blanco","$40","GELAZE","permanente")
esmalte6.imprimir()

labial1 = Labial("Blanco","delgada","5cm","$30")
labial1.imprimir()
labial2 = Labial("Rosa","delgada","5cm","$30")
labial2.imprimir()
labial3 = Labial("Rojo","delgada","5cm","$30")
labial3.imprimir()

cuenta1 = Cuenta("Verdes","circular","Fantasias Miguel","1cm")
cuenta1.imprimir()
cuenta2 = Cuenta("Verdes","circular","Fantasias Miguel","1cm")
cuenta2.imprimir()
cuenta3 = Cuenta("Verdes","circular","Fantasias Miguel","1cm")
cuenta3.imprimir()
cuenta4 = Cuenta("Verdes","circular","Fantasias Miguel","1cm")
cuenta4.imprimir()
cuenta5 = Cuenta("Verdes","circular","Fantasias Miguel","1cm")
cuenta5.imprimir()
cuenta6 = Cuenta("Verdes","circular","Fantasias Miguel","1cm")
cuenta6.imprimir()
cuenta7 = Cuenta("Verdes","circular","Fantasias Miguel","1cm")
cuenta7.imprimir()
cuenta8 = Cuenta("Verdes","circular","Fantasias Miguel","1cm")
cuenta8.imprimir()
cuenta9 = Cuenta("Verdes","circular","Fantasias Miguel","1cm")
cuenta9.imprimir()
cuenta10 = Cuenta("Verdes","circular","Fantasias Miguel","1cm")
cuenta10.imprimir()
cuenta11 = Cuenta("Rojas","circular","Fantasias Miguel","1cm")
cuenta11.imprimir()
cuenta12 = Cuenta("Rojas","circular","Fantasias Miguel","1cm")
cuenta12.imprimir()
cuenta13 = Cuenta("Rojas","circular","Fantasias Miguel","1cm")
cuenta13.imprimir()
cuenta14 = Cuenta("Rojas","circular","Fantasias Miguel","1cm")
cuenta14.imprimir()
cuenta15 = Cuenta("Rosas","circular","Fantasias Miguel","1cm")
cuenta15.imprimir()
cuenta16 = Cuenta("Rosas","circular","Fantasias Miguel","1cm")
cuenta16.imprimir()
cuenta17 = Cuenta("Rosas","circular","Fantasias Miguel","1cm")
cuenta17.imprimir()
cuenta18 = Cuenta("Rosas","circular","Fantasias Miguel","1cm")
cuenta18.imprimir()
cuenta19 = Cuenta("Rosas","circular","Fantasias Miguel","1cm")
cuenta19.imprimir()
cuenta20 = Cuenta("Naranjas","circular","Fantasias Miguel","1cm")
cuenta20.imprimir()
cuenta21 = Cuenta("Naranjas","circular","Fantasias Miguel","1cm")
cuenta21.imprimir()
cuenta22 = Cuenta("Naranjas","circular","Fantasias Miguel","1cm")
cuenta22.imprimir()
cuenta23 = Cuenta("Naranjas","circular","Fantasias Miguel","1cm")
cuenta23.imprimir()
cuenta24 = Cuenta("Naranjas","circular","Fantasias Miguel","1cm")
cuenta24.imprimir()

cinta1 = Cinta("Morada", "120cm","Fantasias Miguel","$10")
cinta1.imprimir()
cinta2 = Cinta("Rosa", "120cm","Fantasias Miguel","$10")
cinta2.imprimir()
cinta3 = Cinta("Verde", "120cm","Fantasias Miguel","$10")
cinta3.imprimir()

telefono = Telefono("Rosa", "Analogico", "15cmx20cm","$500")
telefono.imprimir()

sticker1 = Sticker("Estrella", "Azul","1cm","$0.5")
sticker1.imprimir()
sticker2 = Sticker("Diamante", "Morado","1cm","$0.5")
sticker2.imprimir()
sticker3 = Sticker("Estrella", "Dorado","1cm","$0.5")
sticker3.imprimir()
sticker4 = Sticker("Corazon", "Dorado","1cm","$0.5")
sticker4.imprimir()

pinza1 = Pinza("Azul", "5cm", "Flor", "$5")
pinza1.imprimir()
pinza2 = Pinza("Rosa", "5cm", "Flor", "$5")
pinza2.imprimir()
pinza3 = Pinza("Amarrillo", "5cm", "Flor", "$5")
pinza3.imprimir()
pinza4 = Pinza("Naranja", "5cm", "Flor", "$5")
pinza4.imprimir()
pinza5 = Pinza("Morado", "5cm", "Flor", "$5")
pinza5.imprimir()

Postal1 = Postal("10cm X 15cm", "Texto","Rectangular","$5")
Postal1.imprimir()
Postal2 = Postal("11cm X 12cm", "Fotografia","Rectangular","$5")
Postal2.imprimir()
Postal3 = Postal("12cm X 17cm", "Pintura","Rectangular","$5")
Postal3.imprimir()

marco1 = Marco("15cm X 20cm", "Blanco", "Cuadrado", "Foto de un chico")
marco1.imprimir()
marco2 = Marco("15cm X 20cm", "Crema", "Cuadrado", "Pintura de una chica")
marco2.imprimir()