from clasesFoto1 import Pluma,Tijera,Libreta,Regla,Espejo,Estuche,Pegamento,Marco,Esmalte,Labial,Cuenta,Marcador,Cinta,Telefono,Sticker,Pinza,Postal

pluma1 = Pluma("Rojo","5cm","BIC")
pluma1.imprimir() 
pluma2 = Pluma("Azul","7cm","BIC")
pluma2.imprimir()
pluma3 = Pluma("Verde","7cm","BIC")
pluma3.imprimir()

tijera1 = Tijera("Azul","Mylin")
tijera1.imprimir()

libreta1 = Libreta("Rosa", 100)
libreta1.imprimir()
libreta2 = Libreta("Morada", 100)
libreta2.imprimir()


espejo = Espejo("Corazon", "Rosa")
espejo.imprimir()

estuche = Estuche("Morado","Cuadrado")

regla = Regla("Rosa","Triangular")

pegamento = Pegamento("Pegamento de barra", "Pritt")
pegamento.imprimir()

esmalte1 = Esmalte("Azul")
esmalte1.imprimir()
esmalte2 = Esmalte("Rojo")
esmalte2.imprimir()
esmalte3 = Esmalte("Crema")
esmalte3.imprimir()
esmalte4 = Esmalte("Rosa")
esmalte4.imprimir()
esmalte5 = Esmalte("Rosa")
esmalte5.imprimir()
esmalte6 = Esmalte("Blanco")
esmalte6.imprimir()

labial1 = Labial("Blanco")
labial1.imprimir()
labial2 = Labial("Rosa")
labial2.imprimir()
labial3 = Labial("Rojo")
labial3.imprimir()

cuenta1 = Cuenta("Verdes")
cuenta1.imprimir()
cuenta2 = Cuenta("Verdes")
cuenta2.imprimir()
cuenta3 = Cuenta("Verdes")
cuenta3.imprimir()
cuenta4 = Cuenta("Verdes")
cuenta4.imprimir()
cuenta5 = Cuenta("Verdes")
cuenta5.imprimir()
cuenta6 = Cuenta("Verdes")
cuenta6.imprimir()
cuenta7 = Cuenta("Verdes")
cuenta7.imprimir()
cuenta8 = Cuenta("Verdes")
cuenta8.imprimir()
cuenta9 = Cuenta("Verdes")
cuenta9.imprimir()
cuenta10 = Cuenta("Verdes")
cuenta10.imprimir()
cuenta11 = Cuenta("Rojas")
cuenta11.imprimir()
cuenta12 = Cuenta("Rojas")
cuenta12.imprimir()
cuenta13 = Cuenta("Rojas")
cuenta13.imprimir()
cuenta14 = Cuenta("Rojas")
cuenta14.imprimir()
cuenta15 = Cuenta("Rosas")
cuenta15.imprimir()
cuenta16 = Cuenta("Rosas")
cuenta16.imprimir()
cuenta17 = Cuenta("Rosas")
cuenta17.imprimir()
cuenta18 = Cuenta("Rosas")
cuenta18.imprimir()
cuenta19 = Cuenta("Rosas")
cuenta19.imprimir()
cuenta20 = Cuenta("Naranjas")
cuenta20.imprimir()
cuenta21 = Cuenta("Naranjas")
cuenta21.imprimir()
cuenta22 = Cuenta("Naranjas")
cuenta22.imprimir()
cuenta23 = Cuenta("Naranjas")
cuenta23.imprimir()
cuenta24 = Cuenta("Naranjas")
cuenta24.imprimir()

marcador1 = Marcador("Naranja")
marcador1.imprimir()
marcador2 = Marcador("Morado")
marcador2.imprimir()

cinta1 = Cinta("Morada", "120cm")
cinta1.imprimir()
cinta2 = Cinta("Rosa", "120cm")
cinta2.imprimir()
cinta3 = Cinta("Verde", "120cm")
cinta3.imprimir()

telefono = Telefono("Rosa", "Analogico")
telefono.imprimir()

sticker1 = Sticker("Estrella", "Azule")
sticker1.imprimir()
sticker2 = Sticker("Diamante", "Morado")
sticker2.imprimir()
sticker3 = Sticker("Estrella", "Dorada")
sticker3.imprimir()
sticker4 = Sticker("Corazone", "Dorado")
sticker4.imprimir()

pinza1 = Pinza("Azul", "5cm")
pinza1.imprimir()
pinza2 = Pinza("Rosa", "5cm")
pinza2.imprimir()
pinza3 = Pinza("Amarrillo", "5cm")
pinza3.imprimir()
pinza4 = Pinza("Naranja", "5cm")
pinza4.imprimir()
pinza5 = Pinza("Morado", "5cm")
pinza5.imprimir()

Postal1 = Postal("10cm X 15cm", "Texto")
Postal1.imprimir()
Postal2 = Postal("11cm X 12cm", "Fotografia")
Postal2.imprimir()
Postal3 = Postal("12cm X 17cm", "Pintura")
Postal3.imprimir()

marco1 = Marco("15cm X 20cm", "Blanco", "Cuadrado", "Foto de un chico")
marco1.imprimir()
marco2 = Marco("15cm X 20cm", "Crema", "Cuadrado", "Pintura de una chica")
marco2.imprimir()